// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIxN7tvl0B2D0DyOgZIMlT4zeUZ0aSSw',
    appId: '1:935192493994:web:c21f788fcde66e690e35d3',
    messagingSenderId: '935192493994',
    projectId: 'blue-circle-3166e',
    authDomain: 'blue-circle-3166e.firebaseapp.com',
    storageBucket: 'blue-circle-3166e.firebasestorage.app',
    measurementId: 'G-XE3JPHT43V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuwJIgesCLNzp4FDNdN-kS1vxR6gbGkvA',
    appId: '1:935192493994:android:0a32d3e10ecc22200e35d3',
    messagingSenderId: '935192493994',
    projectId: 'blue-circle-3166e',
    storageBucket: 'blue-circle-3166e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATO8cAF0tEvsGn3kdJMkSkh-sBTcz9PPE',
    appId: '1:935192493994:ios:892605657b0610170e35d3',
    messagingSenderId: '935192493994',
    projectId: 'blue-circle-3166e',
    storageBucket: 'blue-circle-3166e.firebasestorage.app',
    iosClientId: '935192493994-slcs72fnu1kh4g3amg3dk5gb60as9o5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.autismcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATO8cAF0tEvsGn3kdJMkSkh-sBTcz9PPE',
    appId: '1:935192493994:ios:892605657b0610170e35d3',
    messagingSenderId: '935192493994',
    projectId: 'blue-circle-3166e',
    storageBucket: 'blue-circle-3166e.firebasestorage.app',
    iosClientId: '935192493994-slcs72fnu1kh4g3amg3dk5gb60as9o5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.autismcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDIxN7tvl0B2D0DyOgZIMlT4zeUZ0aSSw',
    appId: '1:935192493994:web:31c495f31fe6cca60e35d3',
    messagingSenderId: '935192493994',
    projectId: 'blue-circle-3166e',
    authDomain: 'blue-circle-3166e.firebaseapp.com',
    storageBucket: 'blue-circle-3166e.firebasestorage.app',
    measurementId: 'G-2TEQXZR3KN',
  );
}
